### ISSUE TITLE
Identity not working with BT, seems like it expects that name to be a string

### ISSUE THREAD

**Issue by Sasanidas** [g000001/srfi-236#1]
I was trying the library, when I encounter an error (describe in the title).

More information about the trace:
![Selection_007](https://github.com/g000001/srfi-236/assets/26670956/cba63147-6feb-40ce-abd7-94ff6b5876d2)

I fork the project and add a few changes, but some of them are not related to the issue https://github.com/g000001/srfi-236/compare/main...Sasanidas:srfi-236:main

**Comment by g000001** [comment]
Thank you for your reporting!
fixed https://github.com/g000001/srfi-236/commit/97b9987835682715edaaa0ec30e4a2c8ed21df3e
